diff --git a/Makefile b/Makefile
index 17db63c7..35c10764 100644
--- a/Makefile
+++ b/Makefile
@@ -298,7 +298,7 @@ ifeq ($(ARCH),aarch64)
   HAVE_VM_COMPILED = true
 endif
 
-BASE_CFLAGS =
+BASE_CFLAGS +=
 
 ifeq ($(USE_SYSTEM_JPEG),1)
   BASE_CFLAGS += -DUSE_SYSTEM_JPEG
@@ -632,8 +632,13 @@ endif # *NIX platforms
 
 endif # !MINGW
 
-
-TARGET_CLIENT = $(CNAME)$(ARCHEXT)$(BINEXT)
+ifeq ($(USE_RENDERER_DLOPEN),0)
+RENDERER_ID = _$(RENDERER_DEFAULT)
+endif
+ifeq ($(USE_RENDERER_DLOPEN),1)
+RENDERER_ID = _rdyn
+endif
+TARGET_CLIENT = $(CNAME)$(RENDERER_ID)$(ARCHEXT)$(BINEXT)
 
 TARGET_REND1 = $(RENDERER_PREFIX)_opengl_$(SHLIBNAME)
 TARGET_REND2 = $(RENDERER_PREFIX)_opengl2_$(SHLIBNAME)
